substitutions:
  _REGION: us-central1
  _ARTIFACT_REPOSITORY: origin-v1

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - document-import-service/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/document-import-service:$COMMIT_SHA
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/document-import-service:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/document-import-service:$COMMIT_SHA

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/document-import-service:latest

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/document-import-service:$COMMIT_SHA
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/document-import-service:latest

options:
  logging: CLOUD_LOGGING_ONLY
